### ISSUE TITLE
ulidx is awesome! Can 1.0.0 be released?

### ISSUE THREAD

**Issue by dev-guy** [perry-mitchell/ulidx#10]

**Comment by perry-mitchell** [comment]
Hi, and thanks! Though I can't take credit for the original project this has been built on top of.

Any particular reason you would want a 1.0 release? The current 0.x is well tested and seemingly stable.

I'll release the 1.0 eventually but I usually wait until all of the initial issues and ideas are sorted out, and I'm not sure if we're quite there yet.

**Comment by perry-mitchell** [comment]
Released now.
