### ISSUE TITLE
Cloudflare worker support

### ISSUE THREAD

**Issue by perry-mitchell** [perry-mitchell/ulidx#13]
Support `ulidx` operating in Cloudflare worker contexts, most likely using the monotonic factory feature as active timestamps aren't available. See #5 for more detail.

**Comment by 205g0** [comment]
Any news on this?

**Comment by 205g0** [comment]
From the CF docs: _Date.now() returns the time of the last I/O._

Why is this not enough? Ofc, the more graular the better, but this should be enough for a good entropy (assuming the second part of the string is long enough).

**Comment by 205g0** [comment]
ok, for others driving by, here's the solution: https://github.com/ryan-mars/ulid-workers

@perry-mitchell took me some time to find this, would you have a problem to direct users to ryan's repo in your readme?

**Comment by perry-mitchell** [comment]
@205g0 No news, but I don't currently have access to Cloudflare workers to confirm that ulidx works. Once I can confirm that it functions correctly there, at least from a monotonic standpoint, I'll flag this as being compatible.

**Comment by hamza1311** [comment]
This also does not work in Vercel edge functions. The error message being:
```
✘ [ERROR] Could not resolve "node:crypto"

    node_modules/ulidx/dist/esm/index.js:1:19:
      1 │ import crypto from 'node:crypto';
        ╵                    ~~~~~~~~~~~~~

  The package "node:crypto" wasn't found on the file system but is built into node. Are you trying
  to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

This happens in a SvelteKit application

**Comment by andyjy** [comment]
> This also does not work in Vercel edge functions.

@hamza1311 FWIW I am using `ulidx v2.0.0` successfully under Vercel Edge functions (thus running on Cloudflare workers). 

(With the key note that the timestamp does not increase within the same request due to Cloudflare workers' Date.now() restriction - which doesn't matter for my use-cases.)

> ✘ [ERROR] Could not resolve "node:crypto"
>    node_modules/ulidx/dist/esm/index.js:1:19:

Your error suggests you appear be using a version prior to v2 - it references `node_modules/ulidx/dist/esm/index.js`, whereas v2.0.0 compiles to `ulidx/dist/node/..` and `ulidx/dist/browser/...`.  

Vercel Edge/CF workers requires using the 'browser' import. This is selected automatically for me with ulidx v2 (using webpack+turbopack config provided by Next.JS) according to the exports configured in ulidx's `package.json`.  
(This was implemented in https://github.com/perry-mitchell/ulidx/issues/20.)

**Comment by aaronadamsCA** [comment]
FYI @perry-mitchell, [Wrangler v3](https://www.npmjs.com/package/wrangler) makes it trivial to run a true worker runtime locally now. It now uses `workerd`, the same runtime as Cloudflare Workers.

In my experience, this package already seems to work perfectly on Cloudflare Workers.

The only change that would make it easier to use would be to update your `package.json` `exports` to rename the `"browser"` condition to `"default"` (or add a `"worker"` condition that points to the same build). As it is now, I had to update my Remix esbuild `conditions` from `["worker"]` to `["worker", "browser"]` to get this package loaded; it would be preferable not to tell the build system to load all browser packages just to get this one.

**Comment by perry-mitchell** [comment]
> In my experience, this package already seems to work perfectly on Cloudflare Workers.

That's awesome to hear!

@aaronadamsCA That's great advice - I'll add the worker pointer to the exports shortly and will close this issue then. I'd like to add tests locally using such tools so let's see if that makes it into that release or not.

Thanks for all the eyes on this!

**Comment by perry-mitchell** [comment]
Reopening as I still want to make some final changes before release.

**Comment by perry-mitchell** [comment]
Going to release this now.

If anyone has the time to setup tests using [wrangler](https://www.npmjs.com/package/wrangler), I think this project would definitely benefit from such a guarantee on stability.

**Comment by aaronadamsCA** [comment]
Thanks so much! I can confirm this works perfectly; after upgrading to v2.1.0, we can now `import { ulid } from "ulidx"` in a standard Remix Cloudflare Pages setup with no config changes required.
