### ISSUE TITLE
not fully Crockford's Base32 compatible.

### ISSUE THREAD

**Issue by bluet** [perry-mitchell/ulidx#16]
From [the Crockford's Base32 spec](https://web.archive.org/web/20021223012947/http://www.crockford.com/wrmg/base32.html):
> When decoding, upper and lower case letters are accepted, and i and l will be treated as 1 and o will be treated as 0.
> (...)
> Hyphens (-) can be inserted into symbol strings. This can partition a string into manageable pieces, improving reabability by helping to prevent confusion. Hyphens are ignored during decoding. An application may look for hyphens to assure symbol string correctness.

I can send a PR to fix it.

Another thing:  
Not sure how the *Check Symble* works and if it could affect ulidx. Any idea?

**Comment by perry-mitchell** [comment]
Hi @bluet - While ULIDs make use of Crockford's Base32 spec, it adheres to the [ULID spec](https://github.com/ulid/spec) first and foremost. In the interest of keeping my fork in like with:

 * The [spec here](https://github.com/ulid/spec)
 * Other forks in other languages

I don't think I can support changes that would change how the validity of a ULID is determined. It's not correct imo to validate ULIDs by their Base32 likeness.. they're still ULIDs first.

I appreciate the work you put into this, and I'm sorry that I wasn't able to move this forward. Thanks.

**Comment by bluet** [comment]
Hi @perry-mitchell , thanks for the reply.

As the spec indicates it's Crockford's Base32, the missing part in the original javascript implementation of the compatibility with UILD and Crockford's Base32 has been well discussed.  
As ulidx was originally forked to extend it's life, keep everything up-to-date and complete it, I thought it's about time to fill the missing part.  
But you're the boss and I respect whatever your choice is. Hahaha 

Despite that, adding additional standalone functions for users if they want to fix the ID string from user input (ex, me), doesn't hurt the compatibility with other languages implementations, isn't it?  As long as we don't make it the default behavior.

Just my two cents.

**Comment by perry-mitchell** [comment]
@bluet I've had a think about this and I've changed my mind - I do agree with you. I completely missed that this was all intended as a complimentary set of functions.

I'd accept this PR if you'd be willing to make a couple of changes:

 - Combine all the functionality into a single method. I don't see the value in having them separately as fixUlid does as it says - fixes a ULID in terms of this base32 correctness.
 - Rename said function to something like `fixULIDBase32` so it's clear that it's not just base ULID functionality.

Would you be interested in doing this?

**Comment by bluet** [comment]
So nice to hear that ☺️ you win my respect again. I'll work on that soon.

**Comment by bluet** [comment]
@perry-mitchell Thanks for the merge. Any chance to see 0.5.0 release on npm soon? :D

**Comment by perry-mitchell** [comment]
I will be doing so today 😊

**Comment by perry-mitchell** [comment]
Released under 0.5.0. Thanks @bluet for the work on this, as well as the clear explanations.

**Comment by bluet** [comment]
Thanks! Glad I can help! 😸
