### ISSUE TITLE
export decodeTime?

### ISSUE THREAD

**Issue by grempe** [perry-mitchell/ulidx#2]
I was trying to use `decodeTime()` but its not exported and trying to import from `ulidx/dist/ulid` didn't work with my bundler.

Is it possible to export `decodeTime`, and any other utility functions the same was `ulid` is exported?

https://github.com/perry-mitchell/ulidx/blob/main/source/index.ts#L1

**Comment by perry-mitchell** [comment]
Sure, I don’t see why not. I’d happily accept a PR :)

**Comment by grempe** [comment]
PR submitted. If this looks good, a new release would be great.

**Comment by perry-mitchell** [comment]
Released in 0.2.0 - thanks!

**Comment by DASPRiD** [comment]
> Released in 0.2.0 - thanks!

Don't forget to close this issue ;)
