### ISSUE TITLE
Importing node:crypto breaks compat with edge runtimes (Vercel etc)

### ISSUE THREAD

**Issue by andyjy** [perry-mitchell/ulidx#20]
`UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).`

Looks to have been an oversight(?) in https://github.com/perry-mitchell/ulidx/commit/5b90d022e54e122676fab8ac0c2470c3a05192bc

Reverting this commit fixes things.

Vercel edge runtime provides the web crypto API, which is not the same as / not one of the node-compatible modules that can be loaded with the `node:` prefix: https://nextjs.org/docs/api-reference/edge-runtime

Big thanks for the work on this module!

**Comment by atheck** [comment]
Hi, I have a similar issue in my react-native project. The build crashes with an error: Unable to resolve module node:crypto.

**Comment by perry-mitchell** [comment]
> Vercel edge runtime provides the web crypto API

But this library was never built for the web directly: it was intended to be included in a project that does such bundling, like Webpack etc.. such a process would clean up and remove the crypto module as mentioned at the end of the readme.

It wasn't an oversight as I needed to move to import crypto rather than requiring it - you can see that it was required dynamically in the previous version. This is impossible under ESM as imports are async, and that code path must remain sync.. hence the import.

**Comment by perry-mitchell** [comment]
> I have a similar issue in my react-native project

This was an oversight - There's actually no way to run this on react native, even with the compiled CJS build. 

I might need to consider a web build as well..

And this is why I truly dislike building multiple-output projects 😅. Too many conflicting concerns; and I'm not confident that they're all achievable at the same time.

Anyway - if you have any suggestions please don't hesitate to mention them. I think the "browser" build should solve both of these issues but only because it will strip the crypto import.

**Comment by perry-mitchell** [comment]
To anyone else having these issues: please consider sticking with v0 for now.. there's no need to upgrade just yet as the feature set is the same.

**Comment by andyjy** [comment]
> it was intended to be included in a project that does such bundling, like Webpack etc.. such a process would clean up and remove the crypto module as mentioned at the end of the readme

Got it! Thanks for explaining. 

I figured a new solution that feels cleaner and causes the ESM import of the node crypto module to be stripped correctly - details below. My patch to achieve this is a bit rough around the edges still but if this approach sounds useful I can try put together a PR - let me know if it sounds promising!

~~

I'm using the default Webpack bundling config provided by Next.js (via `next dev` / `next build` commands). With the current code this was failing with the error in my original post rather than stripping the import of the node crypto module as hoped.

By patching the module in a different way I managed to solve the issue building for the Next.js Edge runtime (thus also I think for browser environments (?) although I haven't verified). Specifically the Webpack bundler will strip the import of the node crypto module if it determines via tree-shaking that the import will never be referenced at runtime.

Webpack fails to tree-shake the current code seemingly due to the layers of indirection in the logic that first assigns to `globalCrypto`. To enable successful tree-shaking, I simply patched to add a simple `if` test that returns early with the result of the browser crypto API:

```patch
 function detectPRNG(root) {
+  if (typeof EdgeRuntime === 'string') {
+    return () => {
+      const buffer = new Uint8Array(1);
+      crypto.getRandomValues(buffer);
+      return buffer[0] / 0xff;
+    };
+  }

   ...
```

This worked for my initial test - here I used the test `typeof EdgeRuntime === 'string'` as [recommended specifically for the Vercel Edge runtime](https://vercel.com/docs/concepts/functions/edge-functions/edge-runtime#check-if-you're-running-on-the-edge-runtime); I haven't tested yet but I would next try some simpler `if` tests to try achieve the tree-shaking based on availability of the web crypto API in the global scope rather than the (currently) vendor-specific test for the EdgeRuntime global.

To be able to access the browser crypto API via the global `crypto.` I also renamed the import of the node crypto module (with ESM it may feel cleaner to instead import the required functions directly as named imports): 

```patch
-import crypto from 'node:crypto';
+import { default as nodeCrypto } from 'crypto';

  ... subsequent changes as necessary to reference the renamed import
```

**Comment by atheck** [comment]
Thank you for your efforts. I will try it in my react-native project if the web build is working.

**Comment by perry-mitchell** [comment]
Nice write up!

> This worked for my initial test - here I used the test typeof EdgeRuntime === 'string' as recommended specifically for the Vercel Edge runtime;

So EdgeRuntime is present on Vercel, and I presume Webpack is using such a preset? Perhaps in its "type" field? Electron has such a handler in Webpack as well.

I'd ideally like something more generic (if we're talking about adding logic to avoid Node crypto being bundled).. perhaps if there was something we could add for web detection that would tree shake for normal web output as well as for Vercel edge runtimes.

I suppose you would have had the same success, without editing ulidx, if you'd used `crypto: false` in Webpack's resolve fallbacks - would it be possible for you to try this as an alternative?

**Comment by andyjy** [comment]
> @andyjy Hi! Any chance you've been able to test the crypto: false flag in Webpack?

@perry-mitchell been offline for a few days but I'll find some time to follow up. 

I'm unsure of value of the webpack config test since a) even if it works it would seemingly leave code with unresolved references which seems risky in general even if we believe they won't be called at runtime (and affects all code not just this library), and b) requires tinkering with bundler config which is never pleasant. 

Vs. updating the codebase to resolve the issue via tree-shaking with default bundler config and nothing left at runtime even theoretically unsafe seems much nicer all round.

**Comment by jiw-mh** [comment]
The sensible thing may be to provide a browser and node entry point →. https://github.com/uuidjs/uuid/blob/4de23a6030e65ac72b3b015680f08e7e292681ed/package.json#L24-L46

**Comment by perry-mitchell** [comment]
@jiw-mh Agreed, I'm going to add one now.

**Comment by perry-mitchell** [comment]
So it's mostly done, but I'm a bit concerned about the exports in package.json - I've seen that they can be _extremely_ finicky, and not work at random. I'll probably publish a pre-release for testing.

Do note, however, that I would strongly advise against using the browser version in an environment where build tools like Webpack/Rollup are available. These should be used to bundle the **ESM** build, as it will support tree shaking. I'll add notes as to how to block the `node:crypto` import when using such configurations.

The browser bundle should only be used for injection straight into the browser, when build tools are not present, imo.

**Comment by perry-mitchell** [comment]
@andyjy Getting back to your points, albeit a bit late:

> even if it works it would seemingly leave code with unresolved references
I don't think this is the case, especially with the ESM build. That's the idea: webpack would resolve all imports and remove those that aren't being used, such as `node:crypto`. There's be nothing left that could potentially run later.

> requires tinkering with bundler config which is never pleasant
To each their own I guess, though I prefer to have complete control (where appropriate) over the bundle output. Any default configurations that allow for bundling node's crypto methods without user oversight are flawed imo. I think browser bundles _do take_ a bit of work to get right and should always be customised in terms of your desired outcome.. browser support, feature support.. whether you expect native function X to be included or just be present in the target runtime environment.

I digress; I believe if I provide both a web build (sub-optimal) and instructions on how to use the ESM build with tools such as webpack, that should be enough. I know I could have also build an ESM-web build but this is too much imo.. It starts to get a bit insane with build configs. Almost more code for the configurations than for the actual utility itself 😅.

**Comment by perry-mitchell** [comment]
If someone would want to sanity-check my exports, that'd be swell: https://github.com/perry-mitchell/ulidx/pull/23/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L6

**Comment by jiw-mh** [comment]
@perry-mitchell It would be good to have esm for browser too. esbuild and similar do auto transform.

**Comment by andyjy** [comment]
Big thanks @perry-mitchell - I checked out and built your web-build branch and patched that into my app and it does the job just fine. (NextJS, with both Webpack + Turbopack bundlers).

Regarding your exports - I noticed you have a "browser" entry within the top-level "exports" field, but no top-level "browser" field (unlike e.g. ulid as referenced previously - [see this line](https://github.com/uuidjs/uuid/blob/4de23a6030e65ac72b3b015680f08e7e292681ed/package.json#L41)). It might be worth adding that also - although I don't have a reference for which bundlers may still not support `"exports"`.

**Comment by perry-mitchell** [comment]
> It would be good to have esm for browser too. esbuild and similar do auto transform.

I'm happy for someone to provide such an MR, but I don't currently have the time to add it.

**Comment by perry-mitchell** [comment]
> Regarding your exports - my only observation is you have a "browser" entry within the top-level "exports" field, but no top-level "browser" field for any bundlers/older versions that may not support package "exports" (unlike e.g. uuid as referenced previously - see this line). 

You're right, I'll add that before merging - thanks!

**Comment by perry-mitchell** [comment]
So I've gone back on what I said and created a separate build for each environment anyway:

 * Node ESM
 * Node CJS
 * Browser ESM
 * Browser CJS

So they should all handle as you'd expect. If the tests work I'll probably bundle and release this as 1.1.0 shortly.

**Comment by perry-mitchell** [comment]
Released as 2.0.0-1. Would be great if someone could test that this works 🙏

**Comment by jiw-mh** [comment]
@perry-mitchell Installed it in a project that is setup using vite and esm modules and it works fine.

**Comment by atheck** [comment]
@perry-mitchell It works with react-native again. Thank you! 🎉

**Comment by perry-mitchell** [comment]
Yes, good catch there. I've merged and will add it to the 2.0.0 release!

**Comment by perry-mitchell** [comment]
@atheck If you have a public repository for RN using this library, I'd certainly appreciate a link if you're ok with sharing it :)

**Comment by perry-mitchell** [comment]
2.0.0 released.

**Comment by andyjy** [comment]
Fantastic. Big thanks @perry-mitchell

**Comment by atheck** [comment]
@perry-mitchell At this time I only have a private RN repo, sorry.

FYI: To make jest work again, I need to add these lines to the configuration:

```js
moduleNameMapper: {
  "^ulidx$": require.resolve("ulidx")
}
```
