### ISSUE TITLE
Safari exception "TypeError: crypto.randomUUID is not a function"

### ISSUE THREAD

**Issue by knackstedt** [perry-mitchell/ulidx#36]
Can we add a troubleshooting note that this error will occur when using ulid() on an site served via http. 
When using https, this error will not be thrown as the browser will support randomUUID.

**Comment by perry-mitchell** [comment]
I wonder if there's some confusion here as ulidx doesn't make use of any `randomUUID` method. Ulidx generates random bytes. Could this be from some other library?

That being said I understand that some methods are not available under insecure environments and I would accept documentation PRs that address this.

**Comment by knackstedt** [comment]
It appears I am indeed confused. I'm going to double check what's going on for me, but I'm seeing that error show up specifically when I call `ulid()` and it returns `null`. I wonder if I have a bad polyfill

**Comment by knackstedt** [comment]
By the by, much love for making this library. I really appreciate unique random IDs that are sequenced -- so much easier to deal with for me :smile:

**Comment by knackstedt** [comment]
Turns out my app does have something _terrible_ going on in a polyfill that someone wrote, so this was a red herring unfortunately. 
Thanks for the attempted assist @perry-mitchell ! Greatly appreciated mate :)

**Comment by perry-mitchell** [comment]
>By the by, much love for making this library.

Thanks for saying so! Though remember that I just forked it, the credit lies with the original author. I do enjoy maintaining it though!

>Turns out my app does have something terrible going on in a polyfill that someone wrote, so this was a red herring unfortunately.

Ah, well good you found it! Hope the solution is easy enough.

Hope to see you around mate!
